jobs:
- name: publish
  plan:
  - get: source-code
    trigger: true
  - get: docker-image-resource-source-code
  - put: master
    params:
      build: source-code
    get_params:
      save: true
  - task: test
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: node
          tag: latest
      inputs:
      - name: source-code
      - name: docker-image-resource-source-code
      - name: master
      caches:
      - path: cache/npm
      params:
        TEST_RUNNER: docker
        TEST_REGISTRY: ((test.registry))
        CORRECT_CREDENTIALS: ((test.credentials_good))
        INCORRECT_CREDENTIALS: ((test.credentials_bad))
        NEXUS_WORKAROUND: false
        NORMRF: true
        DOCKER_IMAGE: unit-under-test
      run:
        path: bash
        args:
        - -ec
        - |
          export NPM_CONFIG_CACHE=$PWD/cache/npm
          apt-get update
          apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common \
            iproute2

          curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
          apt-key fingerprint 0EBFCD88
          add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/debian \
            $(lsb_release -cs) \
            stable"
          apt-get update
          apt-get install -y docker-ce docker-ce-cli containerd.io

          . docker-image-resource-source-code/assets/common.sh
          sanitize_cgroups
          start_docker 3 3

          docker load -i "master/image"
          docker tag $(cat "master/image-id") $DOCKER_IMAGE

          cd source-code/test
          npm install
          npm test
  - put: latest
    params:
      load: master
      tag_file: source-code/.git/short_ref
      tag_as_latest: true
    get_params:
      skip_download: true
resources:
- name: source-code
  type: git
  webhook_token: ((webhook_token))
  source:
    uri: https://github.com/timotto/concourse-npm-resource.git
    ignore_path:
    - ci
- name: docker-image-resource-source-code
  type: git
  source:
    uri: https://github.com/concourse/docker-image-resource.git
- name: master
  type: docker-image
  check_every: 24h
  source:
    repository: timotto/concourse-npm-resource
    tag: master
    username: ((dockerhub.username))
    password: ((dockerhub.password))
- name: latest
  type: docker-image
  source:
    repository: timotto/concourse-npm-resource
    tag: latest
    username: ((dockerhub.username))
    password: ((dockerhub.password))
